### ISSUE TITLE
Query Builder Support for where_in, where_or and its variations

### ISSUE THREAD

**Issue by jderr-mx** [kenjis/ci3-to-4-upgrade-helper#12]
**Describe the bug**
Thank you for creating this helper, it is quite useful.
I am working on a large project which makes use of where_in and where_or functions from the query builder. 
Does this helper support those functions?

Looking at https://github.com/kenjis/ci3-to-4-upgrade-helper/blob/1.x/src/CI3Compatible/Database/CI_DB_query_builder.php

It appear that might be the case. 

I am happy to provide more detail if needed. Thanks!

**ci3-to-4-migration-helper version**
Which version (and branch, if applicable) the bug is in.

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.

**Context**
 - OS: [e.g. Windows 99]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 6.5.4]

**Comment by kenjis** [comment]
> Does this helper support those functions?

As you see the code, not yet.

**Comment by kenjis** [comment]
Try #13

**Comment by jderr-mx** [comment]
Wow! Thank you for such a quick response! It seems to be working as intended

**Comment by kenjis** [comment]
Released.
https://github.com/kenjis/ci3-to-4-upgrade-helper/releases/tag/v0.5.0
