### ISSUE TITLE
Bug: $this->abcxyz_model and $this->load->view('abcxyz') no longer work in views in 0.6.0

### ISSUE THREAD

**Issue by sameerkanda** [kenjis/ci3-to-4-upgrade-helper#18]
**Describe the bug**
In our controller we have some code similar to this:
```
$this->load->model("abcxyz_model");
$this->load->view("view1");
```
And in the view our code looks like this:
```
$this->abcxyz_model->get_items();
$this->load->view("view2")
```
Both `$this->abcxyz_model->get_items()` and `$this->load->view("view2")` were working in 0.5.0, but are no longer working in 0.6.0. We get these errors: `Call to a member function get_items() on null` and `Call to a member function view() on null`.

**ci3-to-4-migration-helper version**
0.6.0

**Expected behavior, and steps to reproduce if appropriate**
`$this->abcxyz_model->get_items()` and `$this->load->view("view2")` should work 🤷 

**Context**
 - OS: Linux
 - Web server: php spark serve
 - PHP version: 8.1.2

**Comment by kenjis** [comment]
Try v0.6.1.

**Comment by sameerkanda** [comment]
That seems to work! Thanks @kenjis

**Comment by kenjis** [comment]
Thank you for reporting!
