### ISSUE TITLE
Bug: group_by does not reset

### ISSUE THREAD

**Issue by sameerkanda** [kenjis/ci3-to-4-upgrade-helper#24]
**Describe the bug**
`$this->group_by` does not reset in `Kenjis\CI3Compatible\Database\CI_DB_query_builder:_reset_select()`. This causes `$this->group_by` to remain populated after the query has completed running.

**ci3-to-4-migration-helper version**
0.7.1

**Expected behavior, and steps to reproduce if appropriate**
For example, running `$this->db->select('...')->group_by('...')->get('...')->row_array();` and then `$this->db->get('...')->result_array()` will fail with error "Unknown column '...' in 'group statement'".

**Context**
 - OS: Linux
 - Web server: Docker (not sure)
 - PHP version: 8.x

**Comment by sameerkanda** [comment]
Can this be fixed/updated for version 0.7.1, please? We're on 0.7.1 and don't use 1.x.

**Comment by kenjis** [comment]
Thank you for reporting. Check #25

**Comment by kenjis** [comment]
Fixed in v0.7.2.
