### ISSUE TITLE
Migration Errors

### ISSUE THREAD

**Issue by volkankaban** [kenjis/ci3-to-4-upgrade-helper#9]
Models and Library can't migrate with Tailwindcss, DaisyUI & CodeIgniter 3. How can I send you DM? Thank you. 

```
.drawer
  ├── .drawer-toggle
  ├── .drawer-content
  │    ├── [navbar.php], [header.php], etc.
  │    ├── [page content] ???
  │    └── [footer.php] ???
  └── .drawer-side
       ├── .drawer-overlay
       └── [sidebar.php]
```

**Comment by kenjis** [comment]
Tailwindcss is not related to this tool and CodeIgniter.
This is helper to upgrade CodeIgniter 3 app code.
